name: Upload Python Package (Test PyPiI)

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

  publish:
    runs-on: ubuntu-latest
    environment: test
    permissions:
        id-token: write

    steps:

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
